name: Git-Action-Test

on:
  push:
    branches:
      - master

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
    - name: "пушим проект"
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
       java-version: '17'
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
    - run: mvn clean test
